checks:
    php: true

filter:
    excluded_paths: [vendor/*, test/*]

build:
    environment:
        mysql: 5.5
        php: 7.1.12

    dependencies:
        before:
            - "make prepare"
            - "mkdir build"

    tests:
        override:
            -
                command: "make test"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
