language: php

services: mysql

php:
    - "7.1"

sudo: false

git:
    submodules: false

notifications:
  email: false


before_script:
    - make install
    - make prepare
    - mysql -e 'CREATE DATABASE rdctest;'
    - mysql -uroot rdcTest < resources/sql/setupTestDb.sql
