version: '2'

services:
    web:
        build:
            context: ./
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "80:80"
        links:
            - db
        environment:
            - DB_PORT=3306
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=rdc
        ports:
            - "3306:3306"