exjobb.se:
  hostname: 188.166.122.120
  user: cj
  port: 22
  deploy_path: ~/vhosts/exjobb.se
  configFile: deploy/.ssh_config
  identityFile: /tmp/deploy_rsa
  forwardAgent: true
  multiplexing: false
  options:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: staging
  roles:
    - app
